/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package CALCULADORA;

/**
 * @author Ricardo Illescas
 * @author Santiago Olvera
 * @author Mauricio Vázquez
 * @author Emmanuel Rosales
 * @author Iván Vázquez
 *
 * 27/02/2022 Version 3.0 Creacion de la Interfaz de una calculadora utilizando
 * la clase Calcu para el uso de los metodos
 */
public class Calculadora extends javax.swing.JFrame {

    private Calcu miCalculadora;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infoTxt = new javax.swing.JTextField();
        sevenBt = new javax.swing.JButton();
        eightBt = new javax.swing.JButton();
        nineBt = new javax.swing.JButton();
        divBt = new javax.swing.JButton();
        multBt = new javax.swing.JButton();
        fourBt = new javax.swing.JButton();
        fiveBt = new javax.swing.JButton();
        sixBt = new javax.swing.JButton();
        oneBt = new javax.swing.JButton();
        twoBt = new javax.swing.JButton();
        threeBt = new javax.swing.JButton();
        parentBt = new javax.swing.JButton();
        zeroBt = new javax.swing.JButton();
        parent2Bt = new javax.swing.JButton();
        resBt = new javax.swing.JButton();
        sumBt = new javax.swing.JButton();
        equalsBt = new javax.swing.JButton();
        deleteBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pointBt1 = new javax.swing.JButton();
        deleteBt2 = new javax.swing.JButton();
        negaBt = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infoTxt.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        infoTxt.setForeground(new java.awt.Color(0, 204, 204));
        infoTxt.setToolTipText("");

        sevenBt.setBackground(new java.awt.Color(0, 102, 102));
        sevenBt.setText("7");
        sevenBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtActionPerformed(evt);
            }
        });

        eightBt.setBackground(new java.awt.Color(0, 102, 102));
        eightBt.setText("8");
        eightBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtActionPerformed(evt);
            }
        });

        nineBt.setBackground(new java.awt.Color(0, 102, 102));
        nineBt.setText("9");
        nineBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtActionPerformed(evt);
            }
        });

        divBt.setBackground(new java.awt.Color(0, 102, 102));
        divBt.setText("/");
        divBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divBtActionPerformed(evt);
            }
        });

        multBt.setBackground(new java.awt.Color(0, 102, 102));
        multBt.setText("X");
        multBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multBtActionPerformed(evt);
            }
        });

        fourBt.setBackground(new java.awt.Color(0, 102, 102));
        fourBt.setText("4");
        fourBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtActionPerformed(evt);
            }
        });

        fiveBt.setBackground(new java.awt.Color(0, 102, 102));
        fiveBt.setText("5");
        fiveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtActionPerformed(evt);
            }
        });

        sixBt.setBackground(new java.awt.Color(0, 102, 102));
        sixBt.setText("6");
        sixBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtActionPerformed(evt);
            }
        });

        oneBt.setBackground(new java.awt.Color(0, 102, 102));
        oneBt.setText("1");
        oneBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtActionPerformed(evt);
            }
        });

        twoBt.setBackground(new java.awt.Color(0, 102, 102));
        twoBt.setText("2");
        twoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtActionPerformed(evt);
            }
        });

        threeBt.setBackground(new java.awt.Color(0, 102, 102));
        threeBt.setText("3");
        threeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtActionPerformed(evt);
            }
        });

        parentBt.setBackground(new java.awt.Color(0, 102, 102));
        parentBt.setText("(");
        parentBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentBtActionPerformed(evt);
            }
        });

        zeroBt.setBackground(new java.awt.Color(0, 102, 102));
        zeroBt.setText("0");
        zeroBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtActionPerformed(evt);
            }
        });

        parent2Bt.setBackground(new java.awt.Color(0, 102, 102));
        parent2Bt.setText(")");
        parent2Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parent2BtActionPerformed(evt);
            }
        });

        resBt.setBackground(new java.awt.Color(0, 102, 102));
        resBt.setText("-");
        resBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBtActionPerformed(evt);
            }
        });

        sumBt.setBackground(new java.awt.Color(0, 102, 102));
        sumBt.setText("+");
        sumBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumBtActionPerformed(evt);
            }
        });

        equalsBt.setBackground(new java.awt.Color(0, 102, 102));
        equalsBt.setText("=");
        equalsBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsBtActionPerformed(evt);
            }
        });

        deleteBt.setBackground(new java.awt.Color(0, 102, 102));
        deleteBt.setText("AC");
        deleteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setText("CASIO                           fx-82LA PLUS");

        pointBt1.setBackground(new java.awt.Color(0, 102, 102));
        pointBt1.setText(".");
        pointBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointBt1ActionPerformed(evt);
            }
        });

        deleteBt2.setBackground(new java.awt.Color(0, 102, 102));
        deleteBt2.setText("DEL");
        deleteBt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBt2ActionPerformed(evt);
            }
        });

        negaBt.setBackground(new java.awt.Color(0, 102, 102));
        negaBt.setText("_");
        negaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negaBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oneBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(twoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(threeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(pointBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sevenBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eightBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nineBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fourBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fiveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sixBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(parentBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(zeroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(parent2Bt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(multBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(divBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(negaBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sumBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deleteBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deleteBt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(equalsBt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sevenBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eightBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nineBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(divBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sumBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fourBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sixBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pointBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(negaBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(parentBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(zeroBt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parent2Bt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteBt2)
                            .addComponent(deleteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equalsBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eightBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "8");
    }//GEN-LAST:event_eightBtActionPerformed

    private void divBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "/");
    }//GEN-LAST:event_divBtActionPerformed

    private void multBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "*");
    }//GEN-LAST:event_multBtActionPerformed

    private void nineBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "9");
    }//GEN-LAST:event_nineBtActionPerformed

    private void fiveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "5");
    }//GEN-LAST:event_fiveBtActionPerformed

    private void sixBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "6");
    }//GEN-LAST:event_sixBtActionPerformed

    private void twoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "2");
    }//GEN-LAST:event_twoBtActionPerformed

    private void threeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "3");
    }//GEN-LAST:event_threeBtActionPerformed

    private void zeroBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "0");
    }//GEN-LAST:event_zeroBtActionPerformed

    private void resBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "-");
    }//GEN-LAST:event_resBtActionPerformed

    private void sumBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "+");
    }//GEN-LAST:event_sumBtActionPerformed

    private void equalsBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsBtActionPerformed
        String cadena;
        cadena = infoTxt.getText();
        miCalculadora = new Calcu(cadena);
        if (cadena != "") {
            if (miCalculadora.verificacion() == false) {
                infoTxt.setText("ERROR"); // En caso de que la verificación de los parentesis este mal escrita la calculadora mandafra el mensaje de error
            } else {
                miCalculadora.infijoAPostfijo();
                infoTxt.setText(Double.toString(miCalculadora.evaluar()));
            }
        } else
            infoTxt.setText("");
    }//GEN-LAST:event_equalsBtActionPerformed

    private void deleteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtActionPerformed
        infoTxt.setText("");
    }//GEN-LAST:event_deleteBtActionPerformed

    private void sevenBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "7");
    }//GEN-LAST:event_sevenBtActionPerformed

    private void fourBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "4");
    }//GEN-LAST:event_fourBtActionPerformed

    private void oneBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "1");
    }//GEN-LAST:event_oneBtActionPerformed

    private void parentBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "(");
    }//GEN-LAST:event_parentBtActionPerformed

    private void pointBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointBt1ActionPerformed
        infoTxt.setText(infoTxt.getText() + ".");
    }//GEN-LAST:event_pointBt1ActionPerformed

    private void parent2BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parent2BtActionPerformed
        infoTxt.setText(infoTxt.getText() + ")");
    }//GEN-LAST:event_parent2BtActionPerformed

    /**
     * Este metodo sirve para borrar uno por uno los caracteres escritos en la
     * calculadora
     */
    private void deleteBt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBt2ActionPerformed
        String cadena;
        cadena = infoTxt.getText();

        if (cadena.length() != 0) {
            cadena = cadena.substring(0, cadena.length() - 1);// hace que la cadena quede como la misma cadena sin el ultimo caracter, por lo que cada que se presione el boton borrara uno por uno, pero no hace nada si no hay cadena 
            infoTxt.setText(cadena);
        }
    }//GEN-LAST:event_deleteBt2ActionPerformed

    private void negaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negaBtActionPerformed
        infoTxt.setText(infoTxt.getText() + "_");
    }//GEN-LAST:event_negaBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBt;
    private javax.swing.JButton deleteBt2;
    private javax.swing.JButton divBt;
    private javax.swing.JButton eightBt;
    private javax.swing.JButton equalsBt;
    private javax.swing.JButton fiveBt;
    private javax.swing.JButton fourBt;
    private javax.swing.JTextField infoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multBt;
    private javax.swing.JButton negaBt;
    private javax.swing.JButton nineBt;
    private javax.swing.JButton oneBt;
    private javax.swing.JButton parent2Bt;
    private javax.swing.JButton parentBt;
    private javax.swing.JButton pointBt1;
    private javax.swing.JButton resBt;
    private javax.swing.JButton sevenBt;
    private javax.swing.JButton sixBt;
    private javax.swing.JButton sumBt;
    private javax.swing.JButton threeBt;
    private javax.swing.JButton twoBt;
    private javax.swing.JButton zeroBt;
    // End of variables declaration//GEN-END:variables
}
